name: padel_score
description: "Padel score tracker med real-time sync"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.9
  firebase_auth: ^5.0.0

  # State management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^15.1.2

  # Utils
  uuid: ^4.5.1

  # UI
  google_fonts: ^6.2.1

  # Audio
  audioplayers: ^6.1.0

  # Web localStorage
  web: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
