// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyqgqN_5h-baDo3d7YRj8rfwsfAv4iEik',
    appId: '1:172981973758:web:fe49e63e6800970fb82baf',
    messagingSenderId: '172981973758',
    projectId: 'padel-score-ab0b5',
    authDomain: 'padel-score-ab0b5.firebaseapp.com',
    storageBucket: 'padel-score-ab0b5.firebasestorage.app',
    measurementId: 'G-D13YTKDC4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRzBiYn5ZGkXXhJTst8Ab12YatQ83F_k',
    appId: '1:172981973758:android:a756011501b47118b82baf',
    messagingSenderId: '172981973758',
    projectId: 'padel-score-ab0b5',
    storageBucket: 'padel-score-ab0b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Txpz_56p4QUU27NSNnWYKw8EKaOWsJc',
    appId: '1:172981973758:ios:c725e14684e82c64b82baf',
    messagingSenderId: '172981973758',
    projectId: 'padel-score-ab0b5',
    storageBucket: 'padel-score-ab0b5.firebasestorage.app',
    iosBundleId: 'com.padel.padelScore',
  );
}
